// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnookerPoint.Infrastructure.Persistence;

#nullable disable

namespace SnookerPoint.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SnookerPointDbContext))]
    [Migration("20260729121421_Phase2TableSessions")]
    partial class Phase2TableSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SnookerPoint.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Utc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("Utc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.BillingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumBillableMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundingIncrementMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillingSettings", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.CashMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ShiftId");

                    b.ToTable("CashMovements", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.ClubSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoPrintReceipt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupFolder")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiptWidthMm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SetupCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClubSettings", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.PoolTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("HourlyRate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PoolTables", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.SessionAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Utc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ShiftId");

                    b.ToTable("SessionAdjustments", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.SessionPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PausedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PausedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResumedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResumedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionPauses", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.SessionSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("HourlyRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TableId");

                    b.ToTable("SessionSegments", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingNote")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CountedCash")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpectedCash")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Variance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Open'");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.TableSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckoutStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerLabel")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinalBillableSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinalCharge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinishedShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumBillableMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenedShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundingIncrementMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoidedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("VoidedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTableId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Active', 'Paused')");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("OpenedShiftId");

                    b.HasIndex("SessionNumber")
                        .IsUnique();

                    b.HasIndex("StartUtc");

                    b.HasIndex("Status");

                    b.ToTable("TableSessions", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedOutUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Infrastructure.Persistence.AppInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppInfo", (string)null);
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.CashMovement", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnookerPoint.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.SessionAdjustment", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnookerPoint.Domain.Entities.TableSession", "Session")
                        .WithMany("Adjustments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnookerPoint.Domain.Entities.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.SessionPause", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.TableSession", "Session")
                        .WithMany("Pauses")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.SessionSegment", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.TableSession", "Session")
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnookerPoint.Domain.Entities.PoolTable", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.Shift", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.TableSession", b =>
                {
                    b.HasOne("SnookerPoint.Domain.Entities.PoolTable", null)
                        .WithMany()
                        .HasForeignKey("CurrentTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnookerPoint.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnookerPoint.Domain.Entities.Shift", null)
                        .WithMany()
                        .HasForeignKey("OpenedShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SnookerPoint.Domain.Entities.TableSession", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Pauses");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
